"""
Module: src/optimizers/comparison.py

Responsibility:
    Orchestrate the 5-optimizer comparison study (§8.7).
    Trains the identical 1D ResNet under identical conditions with each optimizer
    and collects training history for convergence analysis.

Study Design:
    - Same model architecture (ResNet1D, ~1.2M params)
    - Same dataset (post-SMOTE training set)
    - Same loss function (FocalLoss, γ=2)
    - Same batch size (128), max epochs (100), early stopping (patience=15)
    - Same random seed for weight initialization and data shuffling
    - Only the optimizer changes between runs

Results Collected (per optimizer, per epoch):
    - Training loss
    - Validation loss
    - Validation accuracy
    - Validation macro F1
    - Per-class F1 (5 classes)
    - Wall-clock time per epoch

Expected Results (per §5.2 / Table 2):
    Baseline CNN + SGD          : 88-91% accuracy, ~72% macro F1
    Baseline CNN + Adam         : 93-95% accuracy, ~81% macro F1
    1D ResNet + AdaGrad         : 91-93% accuracy, ~78% macro F1
    1D ResNet + RMSProp         : 94-96% accuracy, ~84% macro F1
    1D ResNet + Adam (Proposed) : ≥98% accuracy,   ≥93% macro F1

Design Notes:
    - Each run reinitializes the model from the same random seed.
    - Results are saved to results/logs/{optimizer_name}_history.json.
    - Convergence plots are generated by convergence_plots.py.
    - Every performance difference is explained via the Adam paper section
      that theoretically predicts it.
"""

import torch
import torch.nn as nn
from pathlib import Path
from .optimizer_factory import build_optimizer
from ..models.resnet1d import ResNet1D
from ..training.trainer import Trainer
from ..training.focal_loss import FocalLoss
from ..utils.seed import set_seed


OPTIMIZERS_TO_COMPARE = ["sgd", "sgd_momentum", "adagrad", "rmsprop", "adam"]


def run_optimizer_comparison(
    train_loader,
    val_loader,
    device: torch.device,
    random_seed: int = 42,
    save_dir: str = "results/logs",
) -> dict:
    """Run the full 5-optimizer comparison study.

    Returns:
        histories: dict mapping optimizer_name -> training history dict
    """
    raise NotImplementedError


def _train_with_optimizer(
    optimizer_name: str,
    train_loader,
    val_loader,
    device: torch.device,
    random_seed: int,
) -> dict:
    """Train ResNet1D with a single optimizer and return history."""
    raise NotImplementedError
